apiVersion: apps/v1
kind: Deployment
metadata:
  name: aetheris-prod-gateway
  labels:
    app: zt-accelerated-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zt-accelerated-gateway
  template:
    metadata:
      labels:
        app: zt-accelerated-gateway
    spec:
      hostNetwork: true
      containers:
      - name: gateway-core
        # ENFORCING STRICT LOWERCASE PATH STRINGS - Eliminates InvalidImageName blocks
        image: ://amazonaws.com
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: UDP
          name: quic-udp
