replicaCount: 2
image:
  # Updated custom AWS ECR Registry target mapping path
  repository: 123456789.dkr.ecr.us-east-1.amazonaws.com/aetheris-edge
  tag: latest
  pullPolicy: IfNotPresent
service:
  port: 8080
networkPolicy:
  enabled: true
  ingressNamespaceLabel: trusted-ingress-zone
  egressNamespaceLabel: internal-mesh-zone
